name: CD
on:  
  push:
    branches:
    - main
jobs:
  version-bump-and-publish:
    runs-on: ubuntu-latest
    name: Bump version, publish to NPM
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Automated Version Bump
      uses: 'phips28/gh-action-bump-version@master'
      with:
        tag-prefix: 'v'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        version: 19.5
    - name: Get deps
      run: |
        npm ci
    - name: Publish to NPM
      run: |
        npm publish
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}